### PR TITLE
1st remaster

### PR DESCRIPTION
**Pull request by Akorn27**

### CODE REVIEW

**Comment by Qwertylex** [comment]
hmm
thanks
I'm glad to see someone's interested in it

I had my own working copy I fixed up last year somewhere but then I lost it
I remember having to download newer lwjgl natives from sourceforge or something in order to fix it..
but anyway, minecraft made so many changes as of late, we should actually look closer at how it officially does things to try to work from that ...

in the meantime, MultiMC is nice :>

I'm a bit too busy to test your changes so I'll just leave this pull open.

**Comment by IkaSek** [comment]
_**could you possibly link lwjgl natives from sourceforge?**_

**Comment by IkaSek** [comment]
**It screams about classes.**

**Comment by Qwertylex** [comment]
I might find my fixed copy on one of my other HDDs.. I'll try looking for it next week or so.
If not, I could try fixing it up again...
I know a *lot* has changed since this was last touched...
IIRC, the minecraft version it downloads isn't even the latest anymore, it downloads 1.7.x or something like that?
They've put more hoops you gotta jump through to get the version you want...
So much has changed about how they host them now...
https://launcher.mojang.com/v1/objects/1952d94a0784e7abda230aae6a1e8fc0522dba99/client.jar
for example, ^ thats the latest 1.16.4 link.
but it needs assets which are unzipped and loaded from another link... 

I don't know all the details and haven't had enough time to research it all.. 
https://minecraft.gamepedia.com/Java_Edition_1.16.4
the wiki has some info..
also:
https://github.com/MultiMC/MultiMC5

might want to look at how multimc does things since bashcraft is basically a multimc wannabe 
(though bashcraft predates multimc... [bashcraft was written circa 2012])

**Comment by IkaSek** [comment]
i, don't use the "downloading" system, it just isn't efficient i just use the downloads for LWJGL natives, not anything else.

**Comment by IkaSek** [comment]
my version assumes you downloaded game files  _somehow._

**Pull request closed without merging**
